INSERT INTO joke(joketext,jokedate) VALUES ("What do you call a fly without wings? A walk.","2018-12-30");
INSERT INTO joke(joketext,jokedate) VALUES ("When my wife told me to stop impersonating a flamingo, I had to put my foot down.","2018-12-30");
INSERT INTO joke(joketext,jokedate) VALUES ("What do you call someone with no nose? Nobody knows.","2018-12-30");
INSERT INTO joke(joketext,jokedate) VALUES ("What time did the man go to the dentist? Tooth hurt-y.","2018-12-30");
INSERT INTO joke(joketext,jokedate) VALUES ("Why can’t you hear a pterodactyl go to the bathroom? The p is silent.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("How many optometrists does it take to change a light bulb? 1 or 2? 1... or 2?","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("I was thinking about moving to Moscow but there is no point Russian into things.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("Why does Waldo only wear stripes? Because he doesn""t want to be spotted.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("Do you know where you can get chicken broth in bulk? The stock market.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("I used to work for a soft drink can crusher. It was soda pressing.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("A ghost walks into a bar and asks for a glass of vodka but the bar tender says, “sorry we don’t serve spirits”","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("I went to the zoo the other day, there was only one dog in it. It was a shitzu.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("I gave all my dead batteries away today, free of charge.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("Why are skeletons so calm? Because nothing gets under their skin.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("There’s a new type of broom out, it’s sweeping the nation.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("Why don’t seagulls fly over the bay? Because then they’d be bay-gulls!","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("What did celery say when he broke up with his girlfriend? She wasn't right for me, so I really don't carrot all.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("Q: What’s 50 Cent’s name in Zimbabwe? A: 400 Million Dollars.","2019-01-24");
INSERT INTO joke(joketext,jokedate) VALUES ("What's the worst thing about ancient history class? The teachers tend to Babylon.","2019-01-24");